### ISSUE TITLE
host on anaconda?

### ISSUE THREAD

**Issue by suntzuisafterU** [freelunchtheorem/Conditional_Density_Estimation#13]
With the tensorflow requirement for this package installing via conda is a lot easier.  I am interested in using this package but am not going to go through the hassle of solving another tf environment.

**Comment by ferreirafabio** [comment]
Thanks for the feedback @suntzuisafterU . We welcome every helping hand, so we would highly appreciate if you could test and pull request a setup for anaconda.

**Comment by siboehm** [comment]
I might have a look at setting this up on conda-forge sometime over the coming weeks.
