### ISSUE TITLE
No module named "cde.utils"?

### ISSUE THREAD

**Issue by flicious** [freelunchtheorem/Conditional_Density_Estimation#22]
After installing the package I ran into an Error after trying out the demo, can you help me on this please?

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-21-28da70619b4d> in <module>
----> 1 from cde.density_simulation import SkewNormal
      2 from cde.density_estimator import KernelMixtureNetwork
      3 import numpy as np
      4 
      5 """ simulate some data """

~/opt/anaconda3/lib/python3.7/site-packages/cde/__init__.py in <module>
----> 1 from .BaseConditionalDensity import ConditionalDensity

~/opt/anaconda3/lib/python3.7/site-packages/cde/BaseConditionalDensity.py in <module>
      7 import matplotlib.pyplot as plt
      8 import scipy
----> 9 from cde.utils.optimizers import find_root_newton_method, find_root_by_bounding
     10 
     11 

ModuleNotFoundError: No module named 'cde.utils'

**Comment by LPStat-Hub** [comment]
I encountered the same error, is there any update on this at the moment?

**Comment by gradpratik** [comment]
any update on this?

**Comment by trianta2** [comment]
I ran into this issue. Had to create a new environment and downgrade to Python 3.6.

**Comment by dserero** [comment]
Hey install the package by cloning the repo and then using setup.py? 
happened to me but now encountering TensorFlow version errors
