### ISSUE TITLE
Uninstantiated attribute in BaseNNMixtureEstimator

### ISSUE THREAD

**Issue by danrecoskie** [freelunchtheorem/Conditional_Density_Estimation#5]
In the `predict_density` method in `BaseNNMixtureEstimator`, `self.densities` is referenced but is never initialized.
https://github.com/freelunchtheorem/Conditional_Density_Estimation/blob/9d217a0cc02f83c4e6dd41d139ecfa05f11d6038/cde/density_estimator/BaseNNMixtureEstimator.py#L126

**Comment by siboehm** [comment]
You are correct. For the time being, use the `pdf(X, Y)` method instead, it has the same functionality except for requiring you to specify `Y`.
