### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by scuzzar** [freelunchtheorem/Conditional_Density_Estimation#6]
Using model.reset_fit() (i.e. in the default example on git) increases the memory usage.
I did not find a way to reduce it again.
(Running on Windows)

**Comment by jonasrothfuss** [comment]
From our understanding, that's mostly a tensorflow garbage collection problem and we cannot do very much about that. If you have memory problems, the easiest solution is to run stuff in separate OS processes and after a task has been finished, kill the process. For that, you can simply use the Async_Executor in utils.

**Comment by scuzzar** [comment]
This is very possible :-(

Sadly the Async_Executor seams to be involved in the other issue i have #7 ... i will give it a try, or simply use OS Processes for that...
